Webkul\UVDesk\SupportCenterBundle\Entity\TranslatedArticle:
    type: entity
    table: null
    repositoryClass: Webkul\UVDesk\SupportCenterBundle\Repository\TranslatedArticles;
    manyToOne:
        article:
            targetEntity: Article
            inversedBy: translatedArticles
            joinColumn:
                name: article_id
                referenceColumnId: id
                onDelete: cascade                    
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 255    
        
        name:
            type: string
            length: 255
        content:
            type: text
        metaDescription:
            type: string
            length: 255
            column: meta_description
            nullable: true
        keywords:
            type: string
            length: 255
            nullable: true
        metaTitle:
            type: string
            length: 255
            nullable: true
    
    lifecycleCallbacks: { }
