helpdesk_knowledgebase:
    path:     /
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::SolutionList

helpdesk_knowledgebase_header:
    path:     /header/{searchDisable}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::header
    defaults: { searchDisable: false }

default_exception:
    path:     /exception
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Default::exceptionDefault

# Knowledgebase Folders
helpdesk_knowledgebase_folder:
    path:     /folder/{solution}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::Solution
    defaults: { solution: 0 }

helpdesk_knowledgebase_folder_article_collection:
    path:     /folder/{solution}/articles
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::SolutionArticle
    defaults: { solution: 0 }

# Knowledgebase Categories
helpdesk_knowledgebase_category_collection:
    path:     /categories
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::CategoryListing

helpdesk_knowledgebase_category:
    path:     /category/{category}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::Category
    defaults: { category: 0 }

# Knowledgebase Articles
helpdesk_knowledgebase_read_article:
    path:     /article/{article}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::Article
    defaults: { article: 0 }

helpdesk_knowledgebase_read_slug_article:
    path:     /blog/{slug}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::Article
    defaults: { slug: '' }

helpdesk_knowledgebase_rate_article:
    path:     /rating/{articleId}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::RateArticle

# webkul_support_center_Website_solution_article:
#     path:     /folder/{solution}/article/{article}
#     controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::Article
#     defaults: { solution: 0, category: 0, article: 0 }

# webkul_support_center_Website_solution_article_history:
#     path:     /folder/{solution}/article/{article}/{history}
#     controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::Article
#     defaults: { solution: 0, category: 0, article: 0, history: 0 }

# Knowledgebase Search
helpdesk_knowledgebase_search:
    path:     /search/{s}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::Search
    defaults: { s: '' }

helpdesk_knowledgebase_tag:
    path:     /tag/{tag}/{name}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Website::Tag
    defaults: { tag: '', name: '' }
