helpdesk_customer_ticket_collection:
    path:     /tickets
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::Tickets

helpdesk_customer_ticket_collection_xhr:
    path:     /tickets/xhr
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::ticketListXhr

helpdesk_customer_ticket:
    path:     /ticket/view/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::ticketView
    defaults: { id: 0 }

helpdesk_customer_thread_collection_xhr:
    path:     /threads/ajax/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::threadListXhr
    defaults: { id: 0 }

helpdesk_customer_add_ticket_thread:
    path:     /thread/save/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::saveReply
    defaults: { id: 0 }

helpdesk_customer_upload_thread_encoded_image:
    path:     /thread/encoded-images/save/{ticketId}
    controller: Webkul\UVDesk\CoreBundle\Knowledgebase\Thread::base64ImageUpload

helpdesk_customer_rate_ticket:
    path:     /ticket/rate/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::rateTicket
    defaults: { id: 0 }

helpdesk_customer_save_ticket_draft:
    path:     /ticket/draft-save/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::saveDraft
    defaults: { id: 0 }

helpdesk_customer_update_ticket_collaborators_xhr:
    path:     /ticket/collaborator/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::ticketCollaboratorXhr
    defaults: { id: 0 }

helpdesk_customer_create_ticket:
    path:     /create-ticket/
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::ticketAdd
    
helpdesk_customer_create_ticket_success:
    path:     /ticket/success/{email}/{flag}
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::ticketSuccess
    defaults: { email: '', flag: 0 }

helpdesk_customer_download_ticket_attachment:
    path:     /ticket/download/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::downloadAttachment
    defaults: { id: 0 }

helpdesk_customer_download_ticket_attachment_zip:
    path:     /ticket/download-ticket-zip/{threadId}
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Ticket::downloadAttachmentZip
    defaults: { threadId: 0 }

helpdesk_customer_view_ticket_attachment:
    path: /attachment/{id}/view
    controller: Webkul\UVDesk\CoreBundle\Knowledgebase\AttachmentViewer::attachmentView