webkul_support_center_front_login:
    path:     /login
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::login

webkul_support_center_front_social_login:
    path:     /login/{applicationRouteName}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::socialLogin

webkul_support_center_front_google_login:
    path:     /login-google
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::googleLogin

webkul_support_center_front_linkedin_login:
    path:     /login-linkedin
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::linkedinLogin

webkul_support_center_front_forgot_password:
    path:     /forgot-password
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::forgotPassword

webkul_support_center_front_login_post:
    path:     /check
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::check

webkul_support_center_front_logout:
    path:     /logout
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::logout

webkul_support_center_front_account:
    path:     /account
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::Account

webkul_support_center_front_account_merge:
    path:     /account/merge-social
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::mergeSocialAccount

webkul_support_center_front_account_connect_platform:
    path:     /account/connect/{platform}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::connectPlatform

webkul_support_center_front_tickets:
    path:     /tickets
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::Tickets

webkul_support_center_front_tickets_xhr:
    path:     /tickets/xhr
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::ticketListXhr

webkul_support_center_front_ticket_view:
    path:     /ticket/view/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::ticketView
    defaults: { id: 0 }

webkul_support_center_front_custom_fields_xhr:
    path:     /ticket/custom-field/update
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\CustomFields::ticketCustomFieldXHR

webkul_support_center_front_custom_fields_decrypt_xhr:
    path:     /ticket/custom-field/view/{ticketId}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\CustomFields::decryptCustomFieldXHR

# webkul_support_center_front_custom_field_sibling_request:
#     path:     /ticket/{id}/field/siblings
#     controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::siblingCustomField
#     defaults: { id: 0 }

webkul_support_center_front_thread_list_xhr:
    path:     /threads/ajax/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::threadListXhr
    defaults: { id: 0 }

webkul_support_center_front_thread_save:
    path:     /thread/save/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::saveReply
    defaults: { id: 0 }

customer_thread_encoded_image_uploader:
    path:     /thread/encoded-images/save/{ticketId}
    controller: Webkul\UVDesk\CoreBundle\Controller\Thread::base64ImageUpload

webkul_support_center_front_rate_ticket:
    path:     /ticket/rate/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::rateTicket
    defaults: { id: 0 }

webkul_support_center_front_ticket_save_draft:
    path:     /ticket/draft-save/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::saveDraft
    defaults: { id: 0 }

webkul_support_center_front_ticket_collaborator_action_xhr:
    path:     /ticket/collaborator/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::ticketCollaboratorXhr
    defaults: { id: 0 }

download_customer_resources_trigger:
    path:     /resources/backup/confirm
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::initiateCustomerBackup

# download_customer_resources_retrieve:
#     path:     /resources/backup/{confirmationToken}
#     controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::downloadCustomerBackup
#     defaults: { _controller: UVDeskSupportCenterBundle:Customer:downloadCustomerBackup }

# ajax_file_upload_customer:
#     path:     /file-upload
#     controller: Webkul\UVDesk\SupportCenterBundle\Controller\Solution::SolutionList
#     defaults: { _controller: WebkulDefaultBundle:Default:ajaxFileUpload }

# ajax_url_file_customer:
#     path:     /url-upload
#     controller: Webkul\UVDesk\SupportCenterBundle\Controller\Solution::SolutionList
#     defaults: { _controller: WebkulDefaultBundle:Default:ajaxUrlFileUpload }

# ajax_file_remove_customer:
#     path:     /file-remove
#     controller: Webkul\UVDesk\SupportCenterBundle\Controller\Solution::SolutionList
#     defaults: { _controller: WebkulDefaultBundle:Default:ajaxFileRemove }

webkul_support_center_front_ticket_generate:
    path:     /create-ticket/
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::ticketAdd
    
webkul_support_center_front_ticket_generate_success:
    path:     /ticket/success/{email}/{flag}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::ticketSuccess
    defaults: { email: '', flag: 0 }

webkul_support_center_front_download_ticket_attachment:
    path:     /ticket/download/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::downloadAttachment
    defaults: { id: 0 }

webkul_support_center_front_download_ticket_attachment_zip:
    path:     /ticket/download-ticket-zip/{threadId}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Ticket::downloadAttachmentZip
    defaults: { threadId: 0 }

webkul_support_center_front_view_ticket_attachment:
    path: /attachment/{id}/view
    controller: Webkul\UVDesk\CoreBundle\Controller\AttachmentViewer::attachmentView