helpdesk_customer_login:
    path:     /login
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Customer::login

helpdesk_customer_logout:
    path:     /logout
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Customer::logout

helpdesk_customer_account:
    path:     /account
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Customer::Account

helpdesk_customer_forgot_password:
    path:     /forgot-password
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Customer::forgotPassword

helpdesk_customer_account_validation:
    path:     /account-confirmation/{email}/{key}
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Customer::AccountValidation
    defaults: { email: 0, key: 0 }

helpdesk_customer_account_verification:
    path:     /account-verification/{email}/{key}
    controller: Webkul\UVDesk\SupportCenterBundle\Knowledgebase\Customer::AccountVerification
    defaults: { email: 0, key: 0 }

