helpdesk_member_knowledgebase_category_collection:
    path:     /categories
    controller: Webkul\UVDesk\SupportCenterBundle\Workstation\Category::CategoryList

helpdesk_member_knowledgebase_folder_categories_collection:
    path:     /{solution}/categories
    controller: Webkul\UVDesk\SupportCenterBundle\Workstation\Category::CategoryListBySolution
    defaults: { solution: 0 }

helpdesk_member_knowledgebase_category_collection_xhr:
    path:     /categories/ajax
    controller: Webkul\UVDesk\SupportCenterBundle\Workstation\Category::CategoryListXhr

helpdesk_member_knowledgebase_folder_categories_collection_xhr:
    path:     /{solution}/categories/ajax
    controller: Webkul\UVDesk\SupportCenterBundle\Workstation\Category::CategoryListXhr
    defaults: { solution: 0 }

helpdesk_member_knowledgebase_create_category:
    path:     /category/add
    controller: Webkul\UVDesk\SupportCenterBundle\Workstation\Category::Category
    defaults: { panelId: 'knowledgebase' }

helpdesk_member_knowledgebase_update_category:
    path:     /category/edit/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Workstation\Category::Category
    defaults: { panelId: 'knowledgebase', id: 0 }

helpdesk_member_knowledgebase_update_category_xhr:
    path:     /category/ajax/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Workstation\Category::CategoryXhr
    defaults: { id: 0 }
