# ajax_file_upload:
#     path:     /file-upload
#     defaults: { _controller: WebkulDefaultBundle:Default:ajaxFileUpload }

# ajax_url_file:
#     path:     /url-upload
#     defaults: { _controller: WebkulDefaultBundle:Default:ajaxUrlFileUpload }

# ajax_file_remove:
#     path:     /file-remove
#     defaults: { _controller: WebkulDefaultBundle:Default:ajaxFileRemove }

# ajax_service_call:
#     path:     /service-call
#     defaults: { _controller: WebkulDefaultBundle:Default:ajaxServiceCall }


# Solutions
webkul_support_center_solution:
    path:     /solution
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Solution::SolutionList
    defaults: { panelId: 'knowledgebase' }

folder_xhr_actions:
    path:     /solution/ajax
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Solution::SolutionListXhr

folder_add_action:
    path:     /solution/add
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Solution::Solution
    defaults: { panelId: 'knowledgebase' }

folder_edit_action:
    path:     /solution/edit/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Solution::Solution
    defaults: { id: 0 }

folder_ajax_action:
    path:     /solution/ajax/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Solution::SolutionXhr
    defaults: { id: 0 }

#category
webkul_support_center_category:
    path:     /categories
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Category::CategoryList

webkul_support_center_solution_category:
    path:     /{solution}/categories
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Category::CategoryListBySolution
    defaults: { solution: 0 }

category_xhr_actions:
    path:     /categories/ajax
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Category::CategoryListXhr

category_solution_xhr_actions:
    path:     /{solution}/categories/ajax
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Category::CategoryListXhr
    defaults: { solution: 0 }

category_add_action:
    path:     /category/add
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Category::Category
    defaults: { panelId: 'knowledgebase' }

category_edit_action:
    path:     /category/edit/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Category::Category
    defaults: { panelId: 'knowledgebase', id: 0 }

category_mass_action:
    path:     /category/ajax/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Category::CategoryXhr
    defaults: { id: 0 }

#article
webkul_support_center_article:
    path:     /articles
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::ArticleList

webkul_support_center_category_articles:
    path:     /{category}/articles
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::ArticleListByCategory
    defaults: { category: 0 }

webkul_support_center_solution_articles:
    path:     /solution/{solution}/articles
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::ArticleListBySolution
    defaults: { solution: 0 }

article_xhr_actions:
    path:     /articles/ajax
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::ArticleListXhr

article_category_xhr_actions:
    path:     /{category}/articles/ajax
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::ArticleListXhr
    defaults: { category: 0 }

article_solution_xhr_actions:
    path:     /solution/{solution}/articles/ajax
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::ArticleListXhr
    defaults: { solution: 0 }


article_add_action:
    path:     /article/add
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::Article
    defaults: { panelId: 'knowledgebase' }

article_edit_action:
    path:     /article/edit/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::Article
    defaults: { panelId: 'knowledgebase', id: 0 }

article_mass_action:
    path:     /article/ajax
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::ArticleXhr

article_remove_action:
    path:     /article/ajax/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::ArticleXhr
    defaults: { id: 0 }

article_history:
    path:     /articleHistory/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::articleHistoryXhr
    defaults: { id: 0 }

article_related:
    path:     /articleRelated/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::articleRelatedXhr
    defaults: { id: 0 }

translated_article_history:
    path: /translatedArticleHistory/{id}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Article::translatedArticleHistoryXhr
    defaults: { id: 0 }

# Branding Routers
branding_theme:
    path:     /branding/theme/{type}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Branding::theme
    defaults: { panelId: 'settings', type: '' }

branding_spam:
    path:     /block/spam
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Branding::spam
    defaults: { panelId: 'settings', type: '' }

theme_xhr_action:
    path:     /branding/ajax
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Branding::BrandingXhr
