default_exception:
    path:     /exception
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Default::exceptionDefault

webkul_support_center_front_header:
    path:     /header/{searchDisable}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::header
    defaults: { searchDisable: false }

webkul_support_center_front_solutions:
    path:     /
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::SolutionList

webkul_support_center_front_solution:
    path:     /folder/{solution}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::Solution
    defaults: { solution: 0 }

webkul_support_center_front_solution_articles:
    path:     /folder/{solution}/articles
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::SolutionArticle
    defaults: { solution: 0 }

webkul_support_center_front_solution_category:
    path:     /category/{category}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::Category
    defaults: { category: 0 }

webkul_support_center_front_solution_category_article:
    path:     /article/{article}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::Article
    defaults: { article: 0 }

webkul_support_center_front_solution_article_slug:
    path:     /blog/{slug}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::Article
    defaults: { slug: '' }

webkul_support_center_front_solution_categories:
    path:     /categories
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::CategoryListing


webkul_support_center_front_solution_article:
    path:     /folder/{solution}/article/{article}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::Article
    defaults: { solution: 0, category: 0, article: 0 }

webkul_support_center_front_solution_article_history:
    path:     /folder/{solution}/article/{article}/{history}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::Article
    defaults: { solution: 0, category: 0, article: 0, history: 0 }

webkul_support_center_front_solution_article_rating:
    path:     /rating/{articleId}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::RateArticle

webkul_support_center_front_search:
    path:     /search/{s}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::Search
    defaults: { s: '' }

webkul_support_center_front_tag:
    path:     /tag/{tag}/{name}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Front::Tag
    defaults: { tag: '', name: '' }

# user_account_validation:
#     path:     /user-account-confirmation/{email}/{key}
#     controller: Webkul\UVDesk\CoreBundle\Controller\User::AccountValidation
#     defaults: { email: 0, key: 0 }

webkul_support_center_front_account_validation:
    path:     /account-confirmation/{email}/{key}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::AccountValidation
    defaults: { email: 0, key: 0 }

webkul_support_center_front_account_verification:
    path:     /account-verification/{email}/{key}
    controller: Webkul\UVDesk\SupportCenterBundle\Controller\Customer::AccountVerification
    defaults: { email: 0, key: 0 }
