<?php

namespace Webkul\UVDesk\SupportCenterBundle\Repository;

/**
 * ThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllThreads($ticket)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('t')->from('SupportCenterBundle:Thread', 't')
            ->where('t.ticket = :ticket')
            ->setParameter('ticket', $ticket)
            ->getQuery()->getResult();

        return $threads = $qb->getQuery()->getResult();
    }
}
