<?php

namespace Webkul\UVDesk\SupportCenterBundle\Repository;

use Doctrine\ORM\EntityManager;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{ 
    // returns all tickets in array
    public function getAllCustomerTickets($currentUser)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('t')->from('SupportCenterBundle:Ticket', 't')
            ->where('t.customer = :customer')
            ->setParameter('customer', $currentUser);
        
        return $tickets = $qb->getQuery()->getResult();
    }

    public function getTicketById($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('t')->from('SupportCenterBundle:Ticket', 't')
            ->where('t.id = :id')
            ->setParameter('id', $id);

        $ticket = $qb->getQuery()->getResult();

        return $ticket[0];
    }
}
