<?php

namespace Webkul\UVDesk\SupportCenterBundle\Repository;

use Doctrine\ORM\EntityManager;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends \Doctrine\ORM\EntityRepository
{
    private $em;

    // overriden method
    public function findAll()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $qb->select('tp')->from('SupportCenterBundle:Type', 'tp')
            ->andwhere('tp.isActive = 1');

        return $types = $qb->getQuery()->getArrayResult();
    }
}
