<?php

namespace Webkul\UVDesk\SupportCenterBundle\Repository;

/**
 * user_groupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class user_groupRepository extends \Doctrine\ORM\EntityRepository
{
}
