<?php

namespace Webkul\UVDesk\SupportCenterBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Website
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Website extends EntityRepository
{
}
