ajax_file_upload:
    path:     /file-upload
    defaults: { _controller: WebkulDefaultBundle:Default:ajaxFileUpload }

ajax_url_file:
    path:     /url-upload
    defaults: { _controller: WebkulDefaultBundle:Default:ajaxUrlFileUpload }

ajax_file_remove:
    path:     /file-remove
    defaults: { _controller: WebkulDefaultBundle:Default:ajaxFileRemove }

ajax_service_call:
    path:     /service-call
    defaults: { _controller: WebkulDefaultBundle:Default:ajaxServiceCall }


# Solutions
webkul_support_center_solution:
    path:     /solution
    defaults: { _controller: UVDeskSupportCenterBundle:Solution:SolutionList ,panelId: 'knowledgebase'}

folder_xhr_actions:
    path:     /solution/ajax
    defaults: { _controller: UVDeskSupportCenterBundle:Solution:SolutionListXhr }

folder_add_action:
    path:     /solution/add
    defaults: { _controller: UVDeskSupportCenterBundle:Solution:Solution, panelId: 'knowledgebase' }

folder_edit_action:
    path:     /solution/edit/{id}
    defaults: { _controller: UVDeskSupportCenterBundle:Solution:Solution, id:0 }

folder_ajax_action:
    path:     /solution/ajax/{id}
    defaults: { _controller: UVDeskSupportCenterBundle:Solution:SolutionXhr, id:0 }

#category
webkul_support_center_category:
    path:     /categories
    defaults: { _controller: UVDeskSupportCenterBundle:Category:CategoryList }

webkul_support_center_solution_category:
    path:     /{solution}/categories
    defaults: { _controller: UVDeskSupportCenterBundle:Category:CategoryListBySolution, solution:0 }

category_xhr_actions:
    path:     /categories/ajax
    defaults: { _controller: UVDeskSupportCenterBundle:Category:CategoryListXhr }

category_solution_xhr_actions:
    path:     /{solution}/categories/ajax
    defaults: { _controller: UVDeskSupportCenterBundle:Category:CategoryListXhr, solution:0 }

category_add_action:
    path:     /category/add
    defaults: { _controller: UVDeskSupportCenterBundle:Category:Category, panelId: 'knowledgebase' }

category_edit_action:
    path:     /category/edit/{id}
    defaults: { _controller: UVDeskSupportCenterBundle:Category:Category, id: 0 , panelId: 'knowledgebase'}

category_mass_action:
    path:     /category/ajax/{id}
    defaults: { _controller: UVDeskSupportCenterBundle:Category:CategoryXhr, id:0 }


#article
webkul_support_center_article:
    path:     /articles
    defaults: { _controller: UVDeskSupportCenterBundle:Article:ArticleList }

webkul_support_center_category_articles:
    path:     /{category}/articles
    defaults: { _controller: UVDeskSupportCenterBundle:Article:ArticleListByCategory, category:0 }

webkul_support_center_solution_articles:
    path:     /solution/{solution}/articles
    defaults: { _controller: UVDeskSupportCenterBundle:Article:ArticleListBySolution, solution:0 }

article_xhr_actions:
    path:     /articles/ajax
    defaults: { _controller: UVDeskSupportCenterBundle:Article:ArticleListXhr }

article_category_xhr_actions:
    path:     /{category}/articles/ajax
    defaults: { _controller: UVDeskSupportCenterBundle:Article:ArticleListXhr, category:0 }

article_solution_xhr_actions:
    path:     /solution/{solution}/articles/ajax
    defaults: { _controller: UVDeskSupportCenterBundle:Article:ArticleListXhr, solution:0 }


article_add_action:
    path:     /article/add
    defaults: { _controller: UVDeskSupportCenterBundle:Article:Article, panelId: 'knowledgebase' }

article_edit_action:
    path:     /article/edit/{id}
    defaults: { _controller: UVDeskSupportCenterBundle:Article:Article, id:0 , panelId: 'knowledgebase'}

article_mass_action:
    path:     /article/ajax
    defaults: { _controller: UVDeskSupportCenterBundle:Article:ArticleXhr}

article_remove_action:
    path:     /article/ajax/{id}
    defaults: { _controller: UVDeskSupportCenterBundle:Article:ArticleXhr, id:0 }

article_history:
    path:     /articleHistory/{id}
    defaults: { _controller: UVDeskSupportCenterBundle:Article:articleHistoryXhr, id:0 }

article_related:
    path:     /articleRelated/{id}
    defaults: { _controller: UVDeskSupportCenterBundle:Article:articleRelatedXhr, id:0 }

translated_article_history:
    path: /translatedArticleHistory/{id}
    defaults: { _controller: UVDeskSupportCenterBundle:Article:translatedArticleHistoryXhr, id:0 }

# Branding Routers

branding_theme:
    path:     /branding/theme/{type}
    defaults: { _controller: UVDeskSupportCenterBundle:Branding:theme, panelId: 'settings', type : '' }

branding_spam:
    path:     /block/spam
    defaults: { _controller: UVDeskSupportCenterBundle:Branding:spam, type : '', panelId: 'settings' }

theme_xhr_action:
    path:     /branding/ajax
    defaults: { _controller: UVDeskSupportCenterBundle:Branding:BrandingXhr }
