# This file is the entry point to configure the routes for your dependencies.
uvdesk_support_center_bundle_member_routing_resources:
    resource: "@UVDeskSupportCenterBundle/Resources/config/routes/members.yaml"
    prefix:   /{_locale}/member/
    requirements:
        _locale: %app_locales%
    defaults:
        _locale: %locale%

uvdesk_support_center_bundle_customer_routing_resources:
    resource: "@UVDeskSupportCenterBundle/Resources/config/routes/customers.yaml"
    prefix:   /{_locale}/customer/
    requirements:
        _locale: %app_locales%
    defaults:
        _locale: %locale%

uvdesk_support_center_bundle_public_routing_resources:
    resource: "@UVDeskSupportCenterBundle/Resources/config/routes/public.yaml"
    prefix:   /{_locale}/
    requirements:
        _locale: %app_locales%
    defaults:
        _locale: %locale%
